// @generated by queryforge. Do not edit by hand.
pub const QUERYFORGE_VERSION: &str = "0.1.0";
pub const QUERYFORGE_BACKEND: &str = "libsql";
pub const QUERYFORGE_EXECUTION_TARGET: &str = "libsql-native";
pub const QUERYFORGE_FINGERPRINT: &str = "fnv1a64:a7487c8dff4641de";
pub const QUERYFORGE_SCHEMA_FINGERPRINT: &str = "fnv1a64:0090fa7978455e72";
pub const QUERYFORGE_MIGRATION_FINGERPRINT: &str = "fnv1a64:cbf29ce484222325";
