// @generated by queryforge. Do not edit by hand.

// queryforge:query:get_user
pub const GET_USER_SQL: &str = "SELECT id, email, created_at\nFROM users\nWHERE id = ?1;";
pub const GET_USER_FINGERPRINT: &str = "fnv1a64:58237df3447293e9";
pub fn get_user_sql() -> &'static str {
    GET_USER_SQL
}
#[derive(Debug, Clone)]
pub struct GetUserRow {
    pub id: i64,
    pub email: String,
    pub created_at: String,
}
impl TryFrom<queryforge::runtime::libsql_executor::LibsqlRow> for GetUserRow {
    type Error = queryforge::Error;
    fn try_from(
        row: queryforge::runtime::libsql_executor::LibsqlRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.try_get("id")?,
            email: row.try_get("email")?,
            created_at: row.try_get("created_at")?,
        })
    }
}
pub async fn get_user<E>(executor: &E, id: i64) -> queryforge::Result<GetUserRow>
where
    E: queryforge::runtime::libsql_executor::LibsqlExecutor + ?Sized,
{
    let params = vec![queryforge::runtime::libsql_executor::LibsqlValue::from(id)];
    let row = executor.query_one(GET_USER_SQL, &params).await?;
    GetUserRow::try_from(row)
}

// queryforge:query:list_users
pub const LIST_USERS_SQL: &str = "SELECT id, email, created_at\nFROM users\nORDER BY created_at DESC;";
pub const LIST_USERS_FINGERPRINT: &str = "fnv1a64:1de6b5e8d61b1192";
pub fn list_users_sql() -> &'static str {
    LIST_USERS_SQL
}
#[derive(Debug, Clone)]
pub struct ListUsersRow {
    pub id: i64,
    pub email: String,
    pub created_at: String,
}
impl TryFrom<queryforge::runtime::libsql_executor::LibsqlRow> for ListUsersRow {
    type Error = queryforge::Error;
    fn try_from(
        row: queryforge::runtime::libsql_executor::LibsqlRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.try_get("id")?,
            email: row.try_get("email")?,
            created_at: row.try_get("created_at")?,
        })
    }
}
pub async fn list_users<E>(executor: &E) -> queryforge::Result<Vec<ListUsersRow>>
where
    E: queryforge::runtime::libsql_executor::LibsqlExecutor + ?Sized,
{
    let params: Vec<queryforge::runtime::libsql_executor::LibsqlValue> = Vec::new();
    executor
        .query_many(LIST_USERS_SQL, &params)
        .await?
        .into_iter()
        .map(ListUsersRow::try_from)
        .collect()
}

