pub mod libsql_native;
pub mod sqlx_postgres;
pub mod sqlx_sqlite;
pub mod tokio_postgres;

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::config::ExecutionTarget;
use crate::error::Result;
use crate::fingerprint::QUERYFORGE_CODEGEN_VERSION;
use crate::ir::{Nullability, ProjectShape};
use crate::names::{to_pascal_case, to_snake_case};
use crate::nullability::wrap_nullable;
use proc_macro2::{Ident, Span, TokenStream};
use quote::{format_ident, quote};
use syn::{Index, LitStr, Type};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: PathBuf,
    pub content: String,
}

pub fn generate_to_dir(project: &ProjectShape, out_dir: impl AsRef<Path>) -> Result<Vec<PathBuf>> {
    let out_dir = out_dir.as_ref();
    fs::create_dir_all(out_dir)?;

    let mut written = Vec::new();
    for file in render_files(project) {
        write_if_changed(out_dir.join(file.path), &file.content, &mut written)?;
    }

    Ok(written)
}

pub fn write_files_to_dir(
    files: &[GeneratedFile],
    out_dir: impl AsRef<Path>,
) -> Result<Vec<PathBuf>> {
    let out_dir = out_dir.as_ref();
    fs::create_dir_all(out_dir)?;

    let mut written = Vec::new();
    for file in files {
        write_if_changed(out_dir.join(&file.path), &file.content, &mut written)?;
    }

    Ok(written)
}

pub fn render_files(project: &ProjectShape) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    let metadata = metadata_module(project);
    files.push(GeneratedFile {
        path: PathBuf::from("queryforge_metadata.rs"),
        content: metadata,
    });

    let mut module_idents = Vec::new();
    for q in &project.queries {
        let module = q
            .module_path
            .last()
            .cloned()
            .unwrap_or_else(|| "queries".to_string());
        let module_ident = snake_ident(&module);
        if !module_idents
            .iter()
            .any(|existing| existing == &module_ident)
        {
            module_idents.push(module_ident);
        }
    }
    let mod_rs = format_generated_tokens(quote! {
        pub mod queryforge_metadata;
        #( pub mod #module_idents; )*
    });
    files.push(GeneratedFile {
        path: PathBuf::from("mod.rs"),
        content: mod_rs,
    });

    let mut modules = BTreeMap::<String, String>::new();
    for q in &project.queries {
        let module = q
            .module_path
            .last()
            .cloned()
            .unwrap_or_else(|| "queries".to_string());
        let body = match project.execution_target {
            ExecutionTarget::SqlxPostgres => sqlx_postgres::render_query(q),
            ExecutionTarget::TokioPostgres => tokio_postgres::render_query(q),
            ExecutionTarget::LibsqlNative => libsql_native::render_query(q),
            ExecutionTarget::SqlxSqlite => sqlx_sqlite::render_query(q),
        };
        let module_body = modules
            .entry(module)
            .or_insert_with(|| "// @generated by queryforge. Do not edit by hand.\n\n".to_string());
        module_body.push_str(&format!("// queryforge:query:{}\n", q.name));
        module_body.push_str(&body);
        module_body.push('\n');
    }

    for (module, body) in modules {
        files.push(GeneratedFile {
            path: PathBuf::from(format!("{module}.rs")),
            content: body,
        });
    }

    files
}

fn metadata_module(project: &ProjectShape) -> String {
    let version = lit_str(QUERYFORGE_CODEGEN_VERSION);
    let backend = lit_str(&project.backend.to_string());
    let execution_target = lit_str(&project.execution_target.to_string());
    let fingerprint = lit_str(project.fingerprint.as_str());
    let schema_fingerprint = lit_str(project.schema_fingerprint.as_str());
    let migration_fingerprint = lit_str(project.migration_fingerprint.as_str());
    let type_mapping_fingerprint = lit_str(project.type_mapping_fingerprint.as_str());

    format_generated_tokens(quote! {
        pub const QUERYFORGE_VERSION: &str = #version;
        pub const QUERYFORGE_BACKEND: &str = #backend;
        pub const QUERYFORGE_EXECUTION_TARGET: &str = #execution_target;
        pub const QUERYFORGE_FINGERPRINT: &str = #fingerprint;
        pub const QUERYFORGE_SCHEMA_FINGERPRINT: &str = #schema_fingerprint;
        pub const QUERYFORGE_MIGRATION_FINGERPRINT: &str = #migration_fingerprint;
        pub const QUERYFORGE_TYPE_MAPPING_FINGERPRINT: &str = #type_mapping_fingerprint;
    })
}

pub(crate) fn format_generated_tokens(tokens: TokenStream) -> String {
    let file = syn::parse2::<syn::File>(tokens).expect("queryforge generated invalid Rust tokens");
    let mut out = String::from("// @generated by queryforge. Do not edit by hand.\n");
    out.push_str(&prettyplease::unparse(&file));
    out
}

pub(crate) fn format_query_tokens(tokens: TokenStream) -> String {
    let file = syn::parse2::<syn::File>(tokens).expect("queryforge generated invalid Rust tokens");
    prettyplease::unparse(&file)
}

pub(crate) fn lit_str(value: &str) -> LitStr {
    LitStr::new(value, Span::call_site())
}

pub(crate) fn snake_ident(value: &str) -> Ident {
    format_ident!("{}", to_snake_case(value))
}

pub(crate) fn pascal_ident(value: &str) -> Ident {
    format_ident!("{}", to_pascal_case(value))
}

pub(crate) fn upper_ident(value: &str, suffix: &str) -> Ident {
    format_ident!("{}_{}", to_snake_case(value).to_ascii_uppercase(), suffix)
}

pub(crate) fn rust_type(base: &str, nullability: &Nullability) -> Type {
    parse_type(&wrap_nullable(base, nullability))
}

pub(crate) fn parse_type(value: &str) -> Type {
    syn::parse_str(value).unwrap_or_else(|err| panic!("invalid Rust type `{value}`: {err}"))
}

pub(crate) struct RenderedColumn {
    pub field: Ident,
    pub ty: Type,
    pub index: Index,
}

pub(crate) struct RenderedParam {
    pub field: Ident,
    pub ty: Type,
}

pub(crate) fn params_ident(query: &crate::ir::QueryShape) -> Ident {
    pascal_ident(&format!("{}_params", query.name))
}

pub(crate) fn rendered_params(query: &crate::ir::QueryShape) -> Vec<RenderedParam> {
    query
        .params
        .iter()
        .map(|param| RenderedParam {
            field: snake_ident(&param.name),
            ty: parse_type(&param.rust_type.0),
        })
        .collect()
}

pub(crate) fn render_params_struct(query: &crate::ir::QueryShape) -> TokenStream {
    if query.params.is_empty() {
        return TokenStream::new();
    }

    let name = params_ident(query);
    let params = rendered_params(query);
    let fields = params.iter().map(|param| {
        let field = &param.field;
        let ty = &param.ty;
        quote! { pub #field: #ty }
    });

    quote! {
        #[derive(Debug, Clone)]
        pub struct #name {
            #( #fields, )*
        }
    }
}

pub(crate) fn params_arg(query: &crate::ir::QueryShape) -> TokenStream {
    if query.params.is_empty() {
        return TokenStream::new();
    }

    let name = params_ident(query);
    quote! { , params: #name }
}

pub(crate) fn rendered_columns(query: &crate::ir::QueryShape) -> Vec<RenderedColumn> {
    let mut seen = BTreeMap::<String, usize>::new();
    query
        .columns
        .iter()
        .enumerate()
        .map(|(index, column)| {
            let base = to_snake_case(&column.rust_name);
            let count = seen.entry(base.clone()).or_insert(0);
            let field_name = if *count == 0 {
                base
            } else {
                let logical = base.strip_prefix("r#").unwrap_or(&base);
                to_snake_case(&format!("{}_{}", logical, *count + 1))
            };
            *count += 1;

            RenderedColumn {
                field: format_ident!("{}", field_name),
                ty: rust_type(&column.rust_type.0, &column.nullable),
                index: Index::from(index),
            }
        })
        .collect()
}

fn write_if_changed(path: PathBuf, content: &str, written: &mut Vec<PathBuf>) -> Result<()> {
    if path.exists() && fs::read_to_string(&path)? == content {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, content)?;
    written.push(path);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{DatabaseBackend, ExecutionTarget};
    use crate::fingerprint::Fingerprint;
    use crate::ir::{
        Cardinality, InferenceConfidence, Nullability, QueryColumn, QueryDependencies, QueryParam,
        QueryShape, RustType, TypeSource,
    };

    #[test]
    fn writes_multi_query_modules_once_and_is_idempotent() {
        let out_dir = temp_dir("queryforge-codegen");
        let project = ProjectShape {
            backend: DatabaseBackend::Libsql,
            execution_target: ExecutionTarget::LibsqlNative,
            schema_fingerprint: Fingerprint::from_text("schema"),
            migration_fingerprint: Fingerprint::from_text("migrations"),
            type_mapping_fingerprint: Fingerprint::from_text("type-mapping"),
            queries: vec![
                query("get_user", "SELECT * FROM users WHERE id = ?1"),
                query("list_users", "SELECT * FROM users"),
            ],
            fingerprint: Fingerprint::from_text("project"),
        };

        let first = generate_to_dir(&project, &out_dir).unwrap();
        assert!(first.iter().any(|path| path.ends_with("users.rs")));
        let users = fs::read_to_string(out_dir.join("users.rs")).unwrap();
        assert!(users.contains("GET_USER_SQL"));
        assert!(users.contains("LIST_USERS_SQL"));

        let second = generate_to_dir(&project, &out_dir).unwrap();
        assert!(
            second.is_empty(),
            "second generation should not rewrite files"
        );

        fs::remove_dir_all(out_dir).ok();
    }

    #[test]
    fn generated_libsql_native_module_matches_snapshot() {
        let out_dir = temp_dir("queryforge-codegen-snapshot");
        let project = ProjectShape {
            backend: DatabaseBackend::Libsql,
            execution_target: ExecutionTarget::LibsqlNative,
            schema_fingerprint: Fingerprint::from_text("schema"),
            migration_fingerprint: Fingerprint::from_text("migrations"),
            type_mapping_fingerprint: Fingerprint::from_text("type-mapping"),
            queries: vec![row_query()],
            fingerprint: Fingerprint::from_text("project"),
        };

        generate_to_dir(&project, &out_dir).unwrap();

        let metadata = fs::read_to_string(out_dir.join("queryforge_metadata.rs")).unwrap();
        assert_eq!(
            metadata,
            concat!(
                "// @generated by queryforge. Do not edit by hand.\n",
                "pub const QUERYFORGE_VERSION: &str = \"0.1.0\";\n",
                "pub const QUERYFORGE_BACKEND: &str = \"libsql\";\n",
                "pub const QUERYFORGE_EXECUTION_TARGET: &str = \"libsql-native\";\n",
                "pub const QUERYFORGE_FINGERPRINT: &str = \"fnv1a64:ac167f3e17fae47e\";\n",
                "pub const QUERYFORGE_SCHEMA_FINGERPRINT: &str = \"fnv1a64:758d17ff764667b6\";\n",
                "pub const QUERYFORGE_MIGRATION_FINGERPRINT: &str = \"fnv1a64:f7ce72b8b20958c8\";\n",
                "pub const QUERYFORGE_TYPE_MAPPING_FINGERPRINT: &str = \"fnv1a64:12736d3e1114294e\";\n",
            )
        );

        let users = fs::read_to_string(out_dir.join("users.rs")).unwrap();
        assert_eq!(
            users,
            concat!(
                "// @generated by queryforge. Do not edit by hand.\n\n",
                "// queryforge:query:get_user\n",
                "pub const GET_USER_SQL: &str = \"SELECT id, email FROM users WHERE id = ?1\";\n",
                "pub const GET_USER_FINGERPRINT: &str = \"fnv1a64:b1068f146c4596c3\";\n",
                "pub fn get_user_sql() -> &'static str {\n",
                "    GET_USER_SQL\n",
                "}\n",
                "#[derive(Debug, Clone)]\n",
                "pub struct GetUserParams {\n",
                "    pub id: i64,\n",
                "}\n",
                "#[derive(Debug, Clone)]\n",
                "pub struct GetUserRow {\n",
                "    pub id: i64,\n",
                "    pub email: String,\n",
                "}\n",
                "impl TryFrom<queryforge::runtime::libsql_executor::LibsqlRow> for GetUserRow {\n",
                "    type Error = queryforge::Error;\n",
                "    fn try_from(\n",
                "        row: queryforge::runtime::libsql_executor::LibsqlRow,\n",
                "    ) -> Result<Self, Self::Error> {\n",
                "        Ok(Self {\n",
                "            id: row.try_get_index(0)?,\n",
                "            email: row.try_get_index(1)?,\n",
                "        })\n",
                "    }\n",
                "}\n",
                "pub async fn get_user<E>(\n",
                "    executor: &E,\n",
                "    params: GetUserParams,\n",
                ") -> queryforge::Result<GetUserRow>\n",
                "where\n",
                "    E: queryforge::runtime::libsql_executor::LibsqlExecutor + ?Sized,\n",
                "{\n",
                "    let query_params = vec![\n",
                "        queryforge::runtime::libsql_executor::LibsqlValue::from(params.id)\n",
                "    ];\n",
                "    let row = executor.query_one(GET_USER_SQL, &query_params).await?;\n",
                "    GetUserRow::try_from(row)\n",
                "}\n\n",
            )
        );

        fs::remove_dir_all(out_dir).ok();
    }

    #[test]
    fn rendered_columns_are_unique_for_join_duplicate_names() {
        let mut query = row_query();
        query.columns = vec![
            QueryColumn {
                name: "id".to_string(),
                rust_name: "id".to_string(),
                db_type: Some("sqlite:INTEGER".to_string()),
                rust_type: RustType::new("i64"),
                nullable: Nullability::NonNull,
                source: TypeSource::SchemaCatalog,
                confidence: InferenceConfidence::Strong,
            },
            QueryColumn {
                name: "id".to_string(),
                rust_name: "id".to_string(),
                db_type: Some("sqlite:INTEGER".to_string()),
                rust_type: RustType::new("i64"),
                nullable: Nullability::NonNull,
                source: TypeSource::SchemaCatalog,
                confidence: InferenceConfidence::Strong,
            },
            QueryColumn {
                name: "type".to_string(),
                rust_name: "type".to_string(),
                db_type: Some("sqlite:TEXT".to_string()),
                rust_type: RustType::string(),
                nullable: Nullability::Nullable,
                source: TypeSource::SchemaCatalog,
                confidence: InferenceConfidence::Strong,
            },
        ];

        let columns = rendered_columns(&query);
        let fields = columns
            .iter()
            .map(|column| column.field.to_string())
            .collect::<Vec<_>>();

        assert_eq!(fields, vec!["id", "id_2", "r#type"]);
        assert_eq!(columns[0].index.index, 0);
        assert_eq!(columns[1].index.index, 1);
        assert_eq!(columns[2].index.index, 2);
    }

    fn query(name: &str, sql: &str) -> QueryShape {
        QueryShape {
            name: name.to_string(),
            module_path: vec!["users".to_string()],
            source_file: PathBuf::from("queries/users.sql"),
            original_sql: sql.to_string(),
            normalized_sql: sql.to_string(),
            cardinality: Cardinality::Many,
            params: Vec::new(),
            columns: Vec::new(),
            dependencies: QueryDependencies::default(),
            fingerprint: Fingerprint::from_text(&format!("{name}:{sql}")),
        }
    }

    fn row_query() -> QueryShape {
        QueryShape {
            name: "get_user".to_string(),
            module_path: vec!["users".to_string()],
            source_file: PathBuf::from("queries/users.sql"),
            original_sql: "SELECT id, email FROM users WHERE id = ?1".to_string(),
            normalized_sql: "SELECT id, email FROM users WHERE id = ?1".to_string(),
            cardinality: Cardinality::One,
            params: vec![QueryParam {
                name: "id".to_string(),
                position: 1,
                db_type: Some("sqlite:INTEGER".to_string()),
                rust_type: RustType::new("i64"),
                source: TypeSource::SchemaCatalog,
                confidence: InferenceConfidence::Strong,
            }],
            columns: vec![
                QueryColumn {
                    name: "id".to_string(),
                    rust_name: "id".to_string(),
                    db_type: Some("sqlite:INTEGER".to_string()),
                    rust_type: RustType::new("i64"),
                    nullable: Nullability::NonNull,
                    source: TypeSource::SchemaCatalog,
                    confidence: InferenceConfidence::Strong,
                },
                QueryColumn {
                    name: "email".to_string(),
                    rust_name: "email".to_string(),
                    db_type: Some("sqlite:TEXT".to_string()),
                    rust_type: RustType::string(),
                    nullable: Nullability::NonNull,
                    source: TypeSource::SchemaCatalog,
                    confidence: InferenceConfidence::Strong,
                },
            ],
            dependencies: QueryDependencies::default(),
            fingerprint: Fingerprint::from_text("query"),
        }
    }

    fn temp_dir(name: &str) -> PathBuf {
        let unique = format!(
            "{}-{}-{}",
            name,
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        );
        let dir = std::env::temp_dir().join(unique);
        fs::create_dir_all(&dir).unwrap();
        dir
    }
}
